<script setup lang="ts">
// Demonstrates: Route.resource() — one call generates index/create/show/edit,
// all sharing this component. Uses the useRouteName composable.
import { computed } from 'vue'
import { useRouteName } from '@anil-labs/vue-routing'
import { useRoute } from 'vue-router'

const name = useRouteName()
const route = useRoute()
const id = computed(() => route.params['id'])
</script>

<template>
  <h1>Posts <span class="muted">— resource</span></h1>
  <div class="card">
    <p>
      Generated by a single call: <code>Route.resource('posts', ResourcePage)</code> → four
      navigable routes (index, create, show, edit). Server-side actions (store/update/destroy) are
      intentionally not generated client-side.
    </p>
    <p>
      Active route: <b>{{ name }}</b>
      <span v-if="id">
        · id = <b>{{ id }}</b></span
      >
    </p>
    <div class="pill-row">
      <router-link class="btn" :to="{ name: 'posts.index' }">index</router-link>
      <router-link class="btn" :to="{ name: 'posts.create' }">create</router-link>
      <router-link class="btn" :to="{ name: 'posts.show', params: { id: 5 } }">show #5</router-link>
      <router-link class="btn" :to="{ name: 'posts.edit', params: { id: 5 } }">edit #5</router-link>
    </div>
  </div>
</template>
